# Uncomment the next line to define a global platform for your project
 platform :ios, '13.6'
install! 'cocoapods', :disable_input_output_paths => true
target 'RealmExample' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  pod 'RealmSwift','10.7.6'
  pod 'Realm','10.7.6',:modular_headers => true
  pod 'FLAnimatedImage','1.0.16'
  pod 'Moya', '~> 15.0'
  pod 'HandyJSON', '~> 5.0.2'
#   Pods for RealmExample

  target 'RealmExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RealmExampleUITests' do
    # Pods for testing
  end

end
